version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:22.15

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: |
            yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Run Tests
          command: |
            yarn test

      - run:
          name: Lint Source
          command: |
            yarn lint

workflows:
  version: 2
  test:
    jobs:
      - test
